spring.application.name=pokemongohub

spring.datasource.url=jdbc:postgresql://localhost:5432/pokemongohub
spring.datasource.username=postgres
spring.datasource.password=A#!X1e9DqpTUh!1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb.core=DEBUG
